# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

all-errors:
  artifacts:
    paths:
      - flow-types/flow-errors.txt
  script:
    - yarn
    - cd flow-types
    - npx flow --show-all-errors > ./flow-errors.txt || true

typecheck:
  artifacts:
    paths:
      - flow-types/typecheck
  script:
    - yarn
    - ./node_modules/.bin/flow-toolbox --help
