declare module "dnssd" {
  import type { EventEmitter } from "events";

  /**
   * Declaration file generated by dts-gen
   */
  declare export class Advertisement mixins EventEmitter {
    constructor(
      type: string | string[] | ServiceType,
      port: number,
      ...args: any[]
    ): this;
    start(): Advertisement;
    stop(forceImmediate?: boolean, callback?: () => any): void;
    updateTXT(txtObj: any): void;
  }
  declare export class Options {
    name: string;
    host: string;
    txt: any;
    subtypes: string[];
    interface: string;
  }

  /**
   * A service entry as returned by serviceUp
   */
  declare export class Service {
    fullname: string;
    name: string;
    type: ServiceType;
    domain: string;
    host: string;
    port: number;
    addresses: string[];
    txt: any;
    txtRaw: any;
  }
  declare export class ServiceType {
    constructor(...args: Array<string | string[]>): this;
    constructor(args: ServiceType): this;
    name: string;
    protocol: string;
    subtypes: string[];
    toString(): string;
    static all(): ServiceType;
    static tcp(...args: string[]): ServiceType;
    static udp(...args: string[]): ServiceType;
  }
  declare export class Browser mixins EventEmitter {
    constructor(type: string | string[] | ServiceType, ...args: any[]): this;
    start(): Browser;
    stop(): void;
    list(): any[];
  }
  declare export function resolve(
    name: string,
    type: string,
    args: { [key: string]: any }
  ): Promise<any>;

  declare export function resolve4(
    name: string,
    type: string,
    args: { [key: string]: any }
  ): Promise<string>;

  declare export function resolve6(
    name: string,
    type: string,
    args: { [key: string]: any }
  ): Promise<string>;

  declare export function resolveSRV(
    name: string,
    args: { [key: string]: any }
  ): Promise<any>;

  declare export function resolveTXT(
    name: string,
    args: { [key: string]: any }
  ): Promise<any>;

  declare export function resolveService(
    name: string,
    args: { [key: string]: any }
  ): Promise<any>;

  declare export function tcp(...args: string[]): ServiceType;

  declare export function udp(...args: string[]): ServiceType;

  declare export function all(): ServiceType;
}
